/*-------------------------------------------------------------------------
 *
 * mys_parsenodes.h
 *    Definitions for MySQL-compatibility parse tree nodes.
 *
 * These nodes are generated by the MySQL-specific grammar actions and
 * are consumed by the MySQL parse-analysis transform layer before being
 * lowered into standard PostgreSQL Query / utility representations.
 *
 * NodeTag numbers 480--484 are explicitly assigned to avoid colliding
 * with upstream PG18 auto-numbered tags (current boundary: 479).
 *
 * Portions Copyright (c) 2026, HaloLab / openHalo Contributors
 *
 * src/include/nodes/mysql/mys_parsenodes.h
 *
 *-------------------------------------------------------------------------
 */
#ifndef MYS_PARSENODES_H
#define MYS_PARSENODES_H

#include "nodes/nodes.h"
#include "nodes/pg_list.h"

/* ----------------------------------------------------------------
 *    MySQL user-variable reference:  @name  (read)
 * ----------------------------------------------------------------
 */
typedef struct UserVarRef
{
    pg_node_attr(no_query_jumble, nodetag_number(480))

    NodeTag     type;
    char       *userVarName;   /* pstrdup'd identifier after '@'  */
    ParseLoc    location;       /* token start, or -1 if unknown  */
} UserVarRef;

/* ----------------------------------------------------------------
 *    MySQL user-variable assignment:  @name := expr
 * ----------------------------------------------------------------
 */
typedef struct UserVarAssign
{
    pg_node_attr(no_query_jumble, nodetag_number(481))

    NodeTag     type;
    char       *userVarName;   /* pstrdup'd identifier after '@'  */
    Node       *expr;           /* assigned expression (a_expr)    */
    ParseLoc    location;       /* token start, or -1 if unknown  */
} UserVarAssign;

/* ----------------------------------------------------------------
 *    MySQL system-variable reference:  @@name  (reserved)
 * ----------------------------------------------------------------
 */
typedef struct SysVarRef
{
    pg_node_attr(no_query_jumble, nodetag_number(482))

    NodeTag     type;
    char       *sysVarName;    /* pstrdup'd identifier after '@@' */
    ParseLoc    location;       /* token start, or -1 if unknown  */
} SysVarRef;

/* ----------------------------------------------------------------
 *    MySQL SET / variable-assignment utility statement  (reserved)
 * ----------------------------------------------------------------
 */
typedef struct MysVariableSetStmt
{
    pg_node_attr(no_query_jumble, nodetag_number(483))

    NodeTag     type;
    List       *assignments;    /* list of UserVarAssign / SysVarRef */
    ParseLoc    location;       /* statement start                   */
} MysVariableSetStmt;

/* ----------------------------------------------------------------
 *    MySQL SELECT ... INTO @var / INTO OUTFILE  (reserved)
 * ----------------------------------------------------------------
 */
typedef struct MysSelectIntoStmt
{
    pg_node_attr(no_query_jumble, nodetag_number(484))

    NodeTag     type;
    Node       *selectStmt;     /* the wrapped SELECT statement    */
    Node       *intoTarget;     /* INTO target (variable / file)   */
    ParseLoc    location;       /* statement start                  */
} MysSelectIntoStmt;

#endif   /* MYS_PARSENODES_H */
