/*-------------------------------------------------------------------------
 *
 * mys_parsenodes.h
 *    Definitions for MySQL-compatibility parse tree nodes.
 *
 * These nodes are generated by the MySQL-specific grammar actions and
 * are consumed by the MySQL parse-analysis transform layer before being
 * lowered into standard PostgreSQL Query / utility representations.
 *
 * NodeTag numbers 480--484 are explicitly assigned to avoid colliding
 * with upstream PG18 auto-numbered tags (current boundary: 479).
 *
 * Portions Copyright (c) 2026, HaloLab / openHalo Contributors
 *
 * src/include/nodes/mysql/mys_parsenodes.h
 *
 *-------------------------------------------------------------------------
 */
#ifndef MYS_PARSENODES_H
#define MYS_PARSENODES_H

#include "nodes/nodes.h"
#include "nodes/pg_list.h"

/*
 * The MySQL user/system variable expression nodes (UserVarRef,
 * UserVarAssign, SysVarRef) were degraded to standard FuncCall nodes:
 * @name -> pg_catalog.mys_get_user_var('name'), @name := expr ->
 * pg_catalog.mys_set_user_var('name', expr), @@name ->
 * pg_catalog.mys_get_system_variable('name', bool).  Only the statement-
 * level utility nodes remain, consumed by the dialect process_utility.
 */

/* ----------------------------------------------------------------
 *    MySQL SET / variable-assignment utility statement  (reserved)
 * ----------------------------------------------------------------
 */
typedef struct MysVariableSetStmt
{
    pg_node_attr(no_query_jumble, nodetag_number(483))

    NodeTag     type;
    List       *assignments;    /* list of UserVarAssign / SysVarRef */
    ParseLoc    location;       /* statement start                   */
} MysVariableSetStmt;

/* ----------------------------------------------------------------
 *    MySQL SELECT ... INTO @var / INTO OUTFILE  (reserved)
 * ----------------------------------------------------------------
 */
typedef struct MysSelectIntoStmt
{
    pg_node_attr(no_query_jumble, nodetag_number(484))

    NodeTag     type;
    Node       *selectStmt;     /* the wrapped SELECT statement    */
    Node       *intoTarget;     /* INTO target (variable / file)   */
    ParseLoc    location;       /* statement start                  */
} MysSelectIntoStmt;

#endif   /* MYS_PARSENODES_H */
