-- Access method conversion coverage for built-in columnar tables.

CREATE SCHEMA columnar_alter_table_set_access_method;
SET search_path TO columnar_alter_table_set_access_method, public;
SET columnar.compression TO 'none';

CREATE TABLE heap_to_columnar(a int) USING heap;
INSERT INTO heap_to_columnar VALUES (1), (2), (3);

SELECT relam = (SELECT oid FROM pg_am WHERE amname = 'heap') AS starts_as_heap
FROM pg_class
WHERE oid = 'heap_to_columnar'::regclass;

SELECT columnar.alter_table_set_access_method(
    'columnar_alter_table_set_access_method.heap_to_columnar', 'columnar');

SELECT relam = (SELECT oid FROM pg_am WHERE amname = 'columnar') AS converted_to_columnar
FROM pg_class
WHERE oid = 'heap_to_columnar'::regclass;

SELECT count(*), sum(a) FROM heap_to_columnar;

SELECT columnar.alter_table_set_access_method(
    'columnar_alter_table_set_access_method.heap_to_columnar', 'heap');

SELECT relam = (SELECT oid FROM pg_am WHERE amname = 'heap') AS converted_back_to_heap
FROM pg_class
WHERE oid = 'heap_to_columnar'::regclass;

SELECT count(*), sum(a) FROM heap_to_columnar;

CREATE TABLE trigger_convert(a int) USING heap;

CREATE FUNCTION before_stmt_trigger() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    RAISE NOTICE 'before stmt %', TG_OP;
    RETURN NULL;
END;
$$;

CREATE FUNCTION before_row_trigger() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    RAISE NOTICE 'before row % %', TG_OP, NEW.a;
    RETURN NEW;
END;
$$;

CREATE FUNCTION after_row_trigger() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    RAISE NOTICE 'after row % %', TG_OP, NEW.a;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trigger_convert_before_stmt
BEFORE INSERT ON trigger_convert
FOR EACH STATEMENT EXECUTE FUNCTION before_stmt_trigger();

CREATE TRIGGER trigger_convert_before_row
BEFORE INSERT ON trigger_convert
FOR EACH ROW EXECUTE FUNCTION before_row_trigger();

CREATE TRIGGER trigger_convert_after_row
AFTER INSERT ON trigger_convert
FOR EACH ROW EXECUTE FUNCTION after_row_trigger();

INSERT INTO trigger_convert VALUES (1);

SELECT count(*) AS trigger_count_before
FROM pg_trigger
WHERE tgrelid = 'trigger_convert'::regclass;

SELECT columnar.alter_table_set_access_method(
    'columnar_alter_table_set_access_method.trigger_convert', 'columnar');

SELECT count(*) AS trigger_count_after
FROM pg_trigger
WHERE tgrelid = 'trigger_convert'::regclass;

INSERT INTO trigger_convert VALUES (2);

SELECT count(*), sum(a) FROM trigger_convert;

CREATE TABLE indexed_convert(a int, b int) USING heap;
INSERT INTO indexed_convert SELECT i, i * 2 FROM generate_series(1, 100) i;
CREATE INDEX indexed_convert_a_idx ON indexed_convert(a);
CREATE INDEX indexed_convert_expr_idx ON indexed_convert((b + 1));

SELECT indexname FROM pg_indexes
WHERE schemaname = 'columnar_alter_table_set_access_method'
AND tablename = 'indexed_convert'
ORDER BY indexname;

SELECT columnar.alter_table_set_access_method(
    'columnar_alter_table_set_access_method.indexed_convert', 'columnar');

SELECT relam = (SELECT oid FROM pg_am WHERE amname = 'columnar') AS indexed_converted_to_columnar
FROM pg_class
WHERE oid = 'indexed_convert'::regclass;

SELECT indexname FROM pg_indexes
WHERE schemaname = 'columnar_alter_table_set_access_method'
AND tablename = 'indexed_convert'
ORDER BY indexname;

SELECT b FROM indexed_convert WHERE a = 42;

SELECT columnar.alter_table_set_access_method(
    'columnar_alter_table_set_access_method.indexed_convert', 'heap');

SELECT relam = (SELECT oid FROM pg_am WHERE amname = 'heap') AS indexed_converted_back_to_heap
FROM pg_class
WHERE oid = 'indexed_convert'::regclass;

SELECT b FROM indexed_convert WHERE a = 42;

SELECT columnar.alter_table_set_access_method(
    'columnar_alter_table_set_access_method.missing_table', 'columnar');

CREATE TABLE invalid_method(a int);
SELECT columnar.alter_table_set_access_method(
    'columnar_alter_table_set_access_method.invalid_method', 'other');
SELECT columnar.alter_table_set_access_method(
    'columnar_alter_table_set_access_method.invalid_method', 'heap');

CREATE TABLE identity_convert(
    a int,
    b int GENERATED BY DEFAULT AS IDENTITY
);
SELECT columnar.alter_table_set_access_method(
    'columnar_alter_table_set_access_method.identity_convert', 'columnar');

RESET search_path;
DROP SCHEMA columnar_alter_table_set_access_method CASCADE;
