-- ALTER TABLE coverage for built-in columnar tables.

CREATE SCHEMA columnar_alter;
SET search_path TO columnar_alter, public;
SET columnar.compression TO 'none';

CREATE TABLE alter_test(a int, b int, c int) USING columnar;
INSERT INTO alter_test VALUES (1, 2, 3), (4, 5, 6), (7, 8, 9);

ALTER TABLE alter_test DROP COLUMN a;
ANALYZE alter_test;

SELECT * FROM alter_test ORDER BY b, c;
SELECT a FROM alter_test;
INSERT INTO alter_test SELECT 3, 5, 8;
INSERT INTO alter_test SELECT 5, 8;

ALTER TABLE alter_test ADD COLUMN d int;
SELECT * FROM alter_test ORDER BY b, c, d NULLS FIRST;

INSERT INTO alter_test SELECT 3, 5, 8;
SELECT * FROM alter_test ORDER BY b, c, d NULLS FIRST;

ALTER TABLE alter_test ADD COLUMN e int DEFAULT 3;
SELECT * FROM alter_test ORDER BY b, c, d NULLS FIRST, e;

INSERT INTO alter_test SELECT 1, 2, 4, 8;
SELECT * FROM alter_test ORDER BY b, c, d NULLS FIRST, e;

ALTER TABLE alter_test ADD COLUMN f text DEFAULT 'TEXT ME';
INSERT INTO alter_test SELECT 1, 2, 4, 8, 'ABCDEF';

ALTER TABLE alter_test DROP COLUMN c;
ALTER TABLE alter_test DROP COLUMN e;
ANALYZE alter_test;

SELECT * FROM alter_test ORDER BY b, d NULLS FIRST, f;
SELECT count(*) FROM alter_test;
SELECT count(t.*) FROM alter_test t;

ALTER TABLE alter_test ADD COLUMN g boolean DEFAULT isfinite(current_date);
SELECT * FROM alter_test ORDER BY b, d NULLS FIRST, f;
ALTER TABLE alter_test ALTER COLUMN g DROP DEFAULT;

ALTER TABLE alter_test ADD COLUMN h date DEFAULT current_date;
SELECT * FROM alter_test ORDER BY b, d NULLS FIRST, f;
ALTER TABLE alter_test ALTER COLUMN h DROP DEFAULT;

ALTER TABLE alter_test ADD COLUMN i int;
ALTER TABLE alter_test ADD COLUMN j float4;
ALTER TABLE alter_test ADD COLUMN k text;

ALTER TABLE alter_test ALTER COLUMN i TYPE float4;
ALTER TABLE alter_test ALTER COLUMN j TYPE int;
ALTER TABLE alter_test ALTER COLUMN k TYPE varchar(20);
ALTER TABLE alter_test ALTER COLUMN k TYPE text;
ALTER TABLE alter_test RENAME COLUMN k TO k_renamed;
ALTER TABLE alter_test RENAME TO alter_test_renamed;
DROP TABLE alter_test_renamed;

CREATE DOMAIN str_domain AS text NOT NULL;
CREATE TABLE domain_test(a int, b int) USING columnar;
INSERT INTO domain_test VALUES (1, 2), (1, 2);
ALTER TABLE domain_test ADD COLUMN c str_domain;
ALTER TABLE domain_test ADD COLUMN c str_domain DEFAULT 'x';
SELECT * FROM domain_test ORDER BY a, b, c;

BEGIN;
ALTER TABLE domain_test ADD COLUMN d int DEFAULT random();
ROLLBACK;

BEGIN;
ALTER TABLE domain_test ADD COLUMN d serial;
SELECT * FROM domain_test ORDER BY a, b, c, d;
ROLLBACK;

SET default_table_access_method TO columnar;
CREATE TABLE volatile_default AS
SELECT * FROM generate_series(1, 10) id;
ALTER TABLE volatile_default ADD COLUMN col4 int DEFAULT (random() * 10000)::int;
SELECT id, col4 < 10000 AS default_in_range
FROM volatile_default
ORDER BY id;
RESET default_table_access_method;

CREATE TABLE identity_test(a int) USING columnar;
INSERT INTO identity_test VALUES (1), (2), (3);
ALTER TABLE identity_test ADD COLUMN c int GENERATED BY DEFAULT AS IDENTITY;
SELECT * FROM identity_test ORDER BY a;

CREATE TABLE generated_test(x int) USING columnar;
INSERT INTO generated_test VALUES (1), (2), (3);
ALTER TABLE generated_test ADD COLUMN y int GENERATED ALWAYS AS (x + 1) STORED;
SELECT * FROM generated_test ORDER BY x;

BEGIN;
CREATE TABLE local_zero_col(y int);
INSERT INTO local_zero_col VALUES (1), (2);
ALTER TABLE local_zero_col DROP COLUMN y;
CREATE TABLE zero_col_columnar (LIKE local_zero_col) USING columnar;
ALTER TABLE local_zero_col RENAME TO local_zero_col_source;
INSERT INTO zero_col_columnar SELECT * FROM local_zero_col_source;
COMMIT;

SELECT * FROM zero_col_columnar;
SELECT count(*) FROM zero_col_columnar;
INSERT INTO zero_col_columnar DEFAULT VALUES;
INSERT INTO zero_col_columnar DEFAULT VALUES;
SELECT count(*) FROM zero_col_columnar;
VACUUM zero_col_columnar;
ANALYZE zero_col_columnar;
VACUUM FULL zero_col_columnar;
TRUNCATE zero_col_columnar;
SELECT count(*) FROM zero_col_columnar;

CREATE TABLE products (
    product_no int,
    name text,
    price int CONSTRAINT price_constraint CHECK (price > 0)
) USING columnar;

INSERT INTO products VALUES (1, 'bread', 0);
INSERT INTO products VALUES (1, 'bread', 10);
ALTER TABLE products ADD CONSTRAINT dummy_constraint CHECK (price > product_no);
INSERT INTO products VALUES (2, 'shampoo', 1);
INSERT INTO products VALUES (2, 'shampoo', 20);
ALTER TABLE products DROP CONSTRAINT dummy_constraint;
INSERT INTO products VALUES (3, 'pen', 2);
SELECT * FROM products ORDER BY product_no;

CREATE TABLE products_unique(
    product_no int UNIQUE,
    name text,
    price numeric
) USING columnar;

INSERT INTO products_unique VALUES (1, 'bread', 10);
INSERT INTO products_unique VALUES (1, 'bread', 10);

RESET search_path;
DROP SCHEMA columnar_alter CASCADE;
